# syntax=docker/dockerfile:1

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production

WORKDIR /usr/app

RUN npm i -g @nestjs/cli typescript

COPY ./web-server/package*.json .
RUN npm install

COPY ./web-server .
COPY ./shared ./shared

EXPOSE 4000

# Run the application.
CMD npm run start:dev
