CREATE TYPE "public"."warehouse_item_kind" AS ENUM('material', 'hand_tool', 'power_tool');--> statement-breakpoint
CREATE TABLE "warehouse_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warehouse_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"warehouse_id" integer NOT NULL,
	"kind" "warehouse_item_kind" NOT NULL,
	"ref" varchar(64) NOT NULL,
	"quantity" numeric(14, 4) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "warehouse_items_ref_uq" UNIQUE("warehouse_id","kind","ref"),
	CONSTRAINT "warehouse_items_quantity_positive" CHECK ("warehouse_items"."quantity" > 0)
);
--> statement-breakpoint
CREATE TABLE "warehouse_users" (
	"warehouse_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "warehouse_users_warehouse_id_user_id_pk" PRIMARY KEY("warehouse_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "warehouses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warehouses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_id" integer NOT NULL,
	"company_id" integer,
	"name" varchar(100) NOT NULL,
	"address" varchar(300),
	"description" varchar(500),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "warehouse_items" ADD CONSTRAINT "warehouse_items_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_users" ADD CONSTRAINT "warehouse_users_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "warehouse_users_user_idx" ON "warehouse_users" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "warehouses_owner_name_active_uq" ON "warehouses" USING btree ("owner_id",lower("name")) WHERE "warehouses"."is_active";--> statement-breakpoint
CREATE INDEX "warehouses_owner_idx" ON "warehouses" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "warehouses_company_idx" ON "warehouses" USING btree ("company_id");