CREATE TABLE "warehouses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warehouses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_id" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"address" varchar(300),
	"description" varchar(500),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "warehouses_owner_name_active_uq" ON "warehouses" USING btree ("owner_id",lower("name")) WHERE "warehouses"."is_active";--> statement-breakpoint
CREATE INDEX "warehouses_owner_idx" ON "warehouses" USING btree ("owner_id");