CREATE TABLE "hand_tool_variant_params" (
	"variant_id" integer NOT NULL,
	"param_value_id" integer NOT NULL,
	CONSTRAINT "hand_tool_variant_params_variant_id_param_value_id_pk" PRIMARY KEY("variant_id","param_value_id")
);
--> statement-breakpoint
CREATE TABLE "hand_tool_variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hand_tool_variants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(64) NOT NULL,
	"hand_tool_id" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hand_tool_variants_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "hand_tools" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hand_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_ru" varchar(100),
	"name_en" varchar(100),
	"created_by" integer,
	"is_shared" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hand_tools_name_present" CHECK (coalesce("hand_tools"."name_ru", '') <> '' or coalesce("hand_tools"."name_en", '') <> '')
);
--> statement-breakpoint
CREATE TABLE "material_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"name_ru" varchar(100) NOT NULL,
	"name_en" varchar(100) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "material_types_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "material_variant_params" (
	"variant_id" integer NOT NULL,
	"param_value_id" integer NOT NULL,
	CONSTRAINT "material_variant_params_variant_id_param_value_id_pk" PRIMARY KEY("variant_id","param_value_id")
);
--> statement-breakpoint
CREATE TABLE "material_variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_variants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(64) NOT NULL,
	"material_id" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "material_variants_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "materials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "materials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_ru" varchar(150),
	"name_en" varchar(150),
	"description_ru" text,
	"description_en" text,
	"unit_id" integer NOT NULL,
	"type_id" integer,
	"created_by" integer,
	"is_shared" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "materials_name_present" CHECK (coalesce("materials"."name_ru", '') <> '' or coalesce("materials"."name_en", '') <> '')
);
--> statement-breakpoint
CREATE TABLE "param_kinds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "param_kinds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"name_ru" varchar(50) NOT NULL,
	"name_en" varchar(50) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "param_kinds_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "param_values" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "param_values_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind_id" integer,
	"value" numeric(12, 4) NOT NULL,
	"unit_id" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "param_values_kind_value_unit_uq" UNIQUE NULLS NOT DISTINCT("kind_id","value","unit_id")
);
--> statement-breakpoint
CREATE TABLE "power_tools" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "power_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_ru" varchar(100) NOT NULL,
	"name_en" varchar(100) NOT NULL,
	"is_corded" boolean NOT NULL,
	"created_by" integer,
	"is_shared" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seed_history" (
	"filename" text PRIMARY KEY NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "systems" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "systems_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(50) NOT NULL,
	"name_ru" varchar(100),
	"name_en" varchar(100),
	"description_ru" varchar(200),
	"description_en" varchar(200),
	"work_type_id" integer NOT NULL,
	"unit_id" integer NOT NULL,
	"created_by" integer,
	"is_shared" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "systems_title_unique" UNIQUE("title"),
	CONSTRAINT "systems_name_present" CHECK (coalesce("systems"."name_ru", '') <> '' or coalesce("systems"."name_en", '') <> '')
);
--> statement-breakpoint
CREATE TABLE "units" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "units_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(16) NOT NULL,
	"name_ru" varchar(50) NOT NULL,
	"name_en" varchar(50) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "units_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "work_stages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "work_stages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(50) NOT NULL,
	"name_ru" varchar(100),
	"name_en" varchar(100),
	"position" smallint NOT NULL,
	"system_id" integer NOT NULL,
	"created_by" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_stages_title_unique" UNIQUE("title"),
	CONSTRAINT "work_stages_name_present" CHECK (coalesce("work_stages"."name_ru", '') <> '' or coalesce("work_stages"."name_en", '') <> '')
);
--> statement-breakpoint
CREATE TABLE "work_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "work_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"name_ru" varchar(100) NOT NULL,
	"name_en" varchar(100) NOT NULL,
	"created_by" integer,
	"is_shared" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_types_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "hand_tool_variant_params" ADD CONSTRAINT "hand_tool_variant_params_variant_id_hand_tool_variants_id_fk" FOREIGN KEY ("variant_id") REFERENCES "public"."hand_tool_variants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hand_tool_variant_params" ADD CONSTRAINT "hand_tool_variant_params_param_value_id_param_values_id_fk" FOREIGN KEY ("param_value_id") REFERENCES "public"."param_values"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hand_tool_variants" ADD CONSTRAINT "hand_tool_variants_hand_tool_id_hand_tools_id_fk" FOREIGN KEY ("hand_tool_id") REFERENCES "public"."hand_tools"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_variant_params" ADD CONSTRAINT "material_variant_params_variant_id_material_variants_id_fk" FOREIGN KEY ("variant_id") REFERENCES "public"."material_variants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_variant_params" ADD CONSTRAINT "material_variant_params_param_value_id_param_values_id_fk" FOREIGN KEY ("param_value_id") REFERENCES "public"."param_values"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_variants" ADD CONSTRAINT "material_variants_material_id_materials_id_fk" FOREIGN KEY ("material_id") REFERENCES "public"."materials"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "materials" ADD CONSTRAINT "materials_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "materials" ADD CONSTRAINT "materials_type_id_material_types_id_fk" FOREIGN KEY ("type_id") REFERENCES "public"."material_types"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "param_values" ADD CONSTRAINT "param_values_kind_id_param_kinds_id_fk" FOREIGN KEY ("kind_id") REFERENCES "public"."param_kinds"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "param_values" ADD CONSTRAINT "param_values_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "systems" ADD CONSTRAINT "systems_work_type_id_work_types_id_fk" FOREIGN KEY ("work_type_id") REFERENCES "public"."work_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "systems" ADD CONSTRAINT "systems_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_stages" ADD CONSTRAINT "work_stages_system_id_systems_id_fk" FOREIGN KEY ("system_id") REFERENCES "public"."systems"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "hand_tool_variant_params_value_idx" ON "hand_tool_variant_params" USING btree ("param_value_id");--> statement-breakpoint
CREATE INDEX "hand_tool_variants_tool_idx" ON "hand_tool_variants" USING btree ("hand_tool_id");--> statement-breakpoint
CREATE UNIQUE INDEX "hand_tools_name_ru_author_uq" ON "hand_tools" USING btree ("name_ru",coalesce("created_by", 0)) WHERE "hand_tools"."is_active";--> statement-breakpoint
CREATE UNIQUE INDEX "hand_tools_name_en_author_uq" ON "hand_tools" USING btree ("name_en",coalesce("created_by", 0)) WHERE "hand_tools"."is_active";--> statement-breakpoint
CREATE INDEX "material_variant_params_value_idx" ON "material_variant_params" USING btree ("param_value_id");--> statement-breakpoint
CREATE INDEX "material_variants_material_idx" ON "material_variants" USING btree ("material_id");--> statement-breakpoint
CREATE INDEX "materials_unit_idx" ON "materials" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "materials_type_idx" ON "materials" USING btree ("type_id");--> statement-breakpoint
CREATE UNIQUE INDEX "materials_name_ru_author_uq" ON "materials" USING btree ("name_ru",coalesce("created_by", 0)) WHERE "materials"."is_active";--> statement-breakpoint
CREATE UNIQUE INDEX "materials_name_en_author_uq" ON "materials" USING btree ("name_en",coalesce("created_by", 0)) WHERE "materials"."is_active";--> statement-breakpoint
CREATE INDEX "param_values_unit_idx" ON "param_values" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "param_values_kind_idx" ON "param_values" USING btree ("kind_id");--> statement-breakpoint
CREATE INDEX "systems_work_type_idx" ON "systems" USING btree ("work_type_id");--> statement-breakpoint
CREATE INDEX "systems_unit_idx" ON "systems" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "work_stages_system_idx" ON "work_stages" USING btree ("system_id");--> statement-breakpoint
CREATE UNIQUE INDEX "work_stages_system_position_uq" ON "work_stages" USING btree ("system_id","position");