CREATE TABLE IF NOT EXISTS work_type(
   id SMALLSERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS system(
   id SMALLSERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL,
   description VARCHAR (200)
);

CREATE TABLE IF NOT EXISTS component(
   id SMALLSERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS material(
   id SERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS hand_tool(
   id SERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS power_tool(
   id SERIAL PRIMARY KEY,
   title VARCHAR (50) UNIQUE NOT NULL
);