# DOCKER PROD FILE
# docker compose -f compose.prod.yaml build --no-cache
# docker compose -f compose.prod.yaml up --force-recreate --build

networks:
  matli_network:
    name: matli_network
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.16.238.0/24
    #       gateway: 172.16.238.3

services:
  myservices:
    extra_host:
      - host.docker.internal:host-gateway

  web-server:
    build:
      context: ./web-server
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 4000:4000
    env_file:
      - ./secrets/calc-db/.db.env
    environment:
      - DB_HOST=host.docker.internal

  ionic-client:
    build:
      context: ./ionic-client
      dockerfile: ./docker_files/Dockerfile.prod
    ports:
      - 5173:5173

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - ionic-client
      - web-server
