# DOCKER PROD FILE
# docker compose -f compose.prod.yaml build --no-cache
# docker compose -f compose.prod.yaml up --force-recreate --build

networks:
  matli_network:
    name: matli_network

services:
  calc-server:
    image: dmprkp/calc-server:latest
    ports:
      - 4000:4000
    env_file:
      - ./secrets/calc-db/.db.env
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  order-server:
    build:
      context: ./order-server
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 4100:4100
    env_file:
      - ./secrets/order-db/.db.env
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ionic-client:
    build:
      context: ./ionic-client
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 5173:5173

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - ionic-client
      - calc-server
