# DOCKER PROD FILE
# docker compose -f compose.prod.yaml build --no-cache
# docker compose -f compose.prod.yaml up --force-recreate --build

networks:
  matli_network:
    name: matli_network

services:
  calc-server:
    image: dmprkp/calc-server:latest
    platform: linux/amd64
    ports:
      - 4000:4000
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5532
      - DB_USER=/run/secrets/db_user
      - DB_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=/run/secrets/db_name
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # env_file:
    #   - ./secrets/calc-db/.db.env

  order-server:
    build:
      context: ./order-server
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 4100:4100
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5532
      - DB_USER=/run/secrets/db_user
      - DB_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=/run/secrets/db_name
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./order-server/static:/usr/order-server/static
    # env_file:
    #   - ./secrets/order-db/.db.env

  ionic-client:
    build:
      context: ./ionic-client
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - 5173:5173

  nginx:
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ionic-client
      - calc-server
      - order-server

secrets:
  db_password:
    external: true
