FROM node:22-alpine AS build

WORKDIR /usr/admin-client

COPY package*.json ./
RUN npm ci

COPY ./ ./
RUN npm run build


# Та же версия nginx, что у основного шлюза.
FROM nginx:1.25.3-alpine AS runtime

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/admin-client/dist /usr/share/nginx/html

EXPOSE 80
