INSERT INTO hand_tools (id, title, ru_title) VALUES 
(1, 'tape measure', 'рулетка'),
(2, 'level', 'уровень'),
(3, 'pail', 'ведро'),
(4, 'handsaw', 'пила'),
(5, 'metal shears', 'ножницы по металлу'),
(6, 'box cutter', 'нож строительный'),
(7, 'flat paint brush', 'малярная кисть'),
(8, 'paint roller', 'валик малярный'),
(9, 'trowel with teeth', 'гладилка зубчатая'),  
(10, 'hammer', 'молоток'),
(11, 'putty knife', 'шпатель'),
(12, 'plumb bob', 'отвес'),
(13, 'carpenter square', 'угольник плотницкий'),
(14, 'chalk line', 'шнурок мелованный'),
(15, 'block plane', 'рубанок'),
(16, 'nail puller', 'гвоздодёр'),
(17, 'screwdriver', 'отвёртка'),
(18, 'wire stripper', 'инструмент для снятия изоляции'),
(19, 'tin snips', 'ножницы по жести'),
(20, 'pruning shears', 'садовые ножницы'),
(21, 'pipe cutter', 'труборез'),
(22, 'masonry trowel', 'мастерок'),
(23, 'hex key', 'шестигранный ключ'),
(24, 'mallet', 'кувалда'),
(25, 'rule', 'правило')
;