FROM node:20-alpine

ENV NODE_ENV production

WORKDIR /usr/calc-server

RUN npm i -g typescript
RUN npm i -g @nestjs/cli

COPY ./package*.json ./
RUN npm install

COPY ./ ./

EXPOSE 4000

CMD npm run start:dev