FROM nginx:1.25.3

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i \
    -e '/#http servers/,/# https server/d' \
    -e 's/listen 443 ssl;/listen 80;/' \           
    -e '/ssl_certificate/d' \                       
    -e '/server_name/d' \                      
    -e '/ssl_certificate_key/d' \                  
    -e '/ssl_protocols/d' \                        
    -e '/ssl_ciphers/d' \                          
    -e '/add_header/d' \                           
    -e '/return 301 https/d' \                     
    -e '/^[[:space:]]*#.*$/d' \                   
    /etc/nginx/conf.d/default.conf