FROM node:20-alpine

ENV NODE_ENV production

WORKDIR /usr/order-server

RUN npm i -g typescript
RUN npm i -g @nestjs/cli

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY ./ ./ 

EXPOSE 4100
RUN npm run prisma:gen

# npx prisma migrate dev --name init
# npx prisma generate (outside container)
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
