FROM node:20-alpine

ENV NODE_ENV production

WORKDIR /usr/order-server

RUN npm i -g typescript
RUN npm i -g @nestjs/cli

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY ./ ./ 

# Run TypeScript compiler
RUN npm run build

EXPOSE 4100

CMD npm run start:dev
