FROM node:22-alpine AS build

WORKDIR /usr/user-server

COPY package*.json ./
RUN npm ci

COPY ./ ./
RUN npm run build


FROM node:22-alpine AS runtime

ENV NODE_ENV=production
WORKDIR /usr/user-server

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /usr/user-server/dist ./dist
COPY --from=build /usr/user-server/drizzle ./drizzle

USER node
EXPOSE 4200

CMD ["sh", "-c", "node dist/db/migrate && node dist/main"]
