FROM node:20.12-bookworm

ENV NODE_ENV production

WORKDIR /usr/web-server
RUN npm install -g npm@10.5.2

RUN npm i -g @nestjs/cli typescript@5.2.2 @types/node

COPY ./package.json ./
RUN npm install

COPY ./ ./

EXPOSE 4000

CMD npm run start:dev
