FROM node:22-alpine AS build

WORKDIR /usr/mail-server

COPY package*.json ./
RUN npm ci

COPY ./ ./
RUN npm run build


FROM node:22-alpine AS runtime

ENV NODE_ENV=production
WORKDIR /usr/mail-server

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /usr/mail-server/dist ./dist

USER node
EXPOSE 4700

CMD ["node", "dist/main"]
