INSERT INTO power_tools (id, title, ru_title, corded) VALUES 
(1, 'impact driver', 'ударный гайковерт', FALSE),
(2, 'impact driver', 'ударный гайковерт', TRUE),
(3, 'pistol-grip drill', 'шуруповерт', FALSE),
(4, 'pistol-grip drill', 'дрель', TRUE),
(5, 'hammer drill', 'ударный шуруповерт', FALSE),
(6, 'hammer drill', 'ударная дрель', TRUE),
(7, 'angle grinder', 'угловая шлифмашина', FALSE),
(8, 'angle grinder', 'угловая шлифмашина', TRUE),
(9, 'circular saw', 'циркулярная пила', FALSE),
(10, 'circular saw', 'циркулярная пила', TRUE),
(11, 'jigsaw', 'лобзик', FALSE),
(12, 'jigsaw', 'лобзик', TRUE),
(13, 'belt sander', 'ленточная шлифмашина', FALSE),
(14, 'belt sander', 'ленточная шлифмашина', TRUE),
(15, 'rotary hammer', 'перфоратор', FALSE),
(16, 'rotary hammer', 'перфоратор', TRUE),
(17, 'table saw', 'настольная пила', FALSE),
(18, 'table saw', 'настольная пила', TRUE),
(19, 'reciprocating saw', 'сабельная пила', FALSE),
(20, 'reciprocating saw', 'сабельная пила', TRUE),
(21, 'heat gun', 'термофен', FALSE),
(22, 'heat gun', 'термофен', TRUE),
(23, 'power planer', 'электрический рубанок', FALSE),
(24, 'power planer', 'электрический рубанок', TRUE),
(25, 'mud mixer', 'миксер', TRUE)
;