# syntax=docker/dockerfile:1

# docker build -t ionic-client -f Dockerfile.prod .
# docker run -p 5173:5173 --name ionic-client ionic-client

ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV development

RUN npm i -g vue-tsc vite @types/node

WORKDIR /usr/app

COPY ./package.json ./ 

RUN npm install

COPY ./ ./

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview"]