name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to remote server
        run: |
          rsync -avz --exclude='.git' -e "ssh -p 5022" ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/App/

      - name: Deploy services with Docker Compose
        run: |
          ssh -p 5022 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /home/${{ secrets.REMOTE_USER }}/app
            docker compose -f compose.prod.yaml down
            docker compose -f compose.prod.yaml up --build -d
          EOF
