name: Deploy to Remote Server

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 5022 ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy files to remote server
        run: |
          rsync -avz --exclude='.git' -e "ssh -p 5022" ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/mnt/tank/matli/material_request

      - name: Deploy services with Docker Compose
        run: |
          ssh -p 5022 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /mnt/tank/matli/material_request 
            sudo docker compose -f compose.prod.yaml down
            sudo docker rmi matli-nginx
            sudo docker rmi dmprkp/calc-server
            sudo docker compose -f compose.prod.yaml build --no-cache
            sudo docker compose -f compose.prod.yaml up -d
            sudo docker system prune -f
            sudo docker ps -a | grep -q "matli-nginx" && echo "Nginx контейнер запущен" || echo "Nginx контейнер не запущен"
            sudo docker ps -a | grep -q "dmprkp/calc-server" && echo "Calc сервер контейнер запущен" || echo "Calc сервер контейнер не запущен"
            curl -s -f https://zayavka.xyz/ && echo "Приложение доступно" || echo "Приложение не доступно"
          EOF
